# ------ Build Stage -------
FROM node:18 AS builder

WORKDIR /app

COPY package*.json /app

RUN npm install

COPY . .

# ---- Multi-Stage -------

FROM node:18-alpine

WORKDIR /app

COPY package*.json /app

RUN npm install --only=production

COPY --from=builder /app .

EXPOSE 3000

CMD ["npm","start"]
